/// Local Database Setup using Hive
/// For offline-first data storage
library;

import 'package:hive_flutter/hive_flutter.dart';
// Import other models as we create them

class LocalDatabase {
  static const String _userBoxName = 'users';
  static const String _childBoxName = 'children';
  static const String _pregnancyBoxName = 'pregnancies';
  static const String _visitBoxName = 'visits';
  static const String _immunizationBoxName = 'immunizations';
  static const String _growthBoxName = 'growth_measurements';
  static const String _appointmentBoxName = 'appointments';
  static const String _syncQueueBoxName = 'sync_queue';
  static const String _settingsBoxName = 'settings';

  /// Initialize Hive and register adapters
  static Future<void> initialize() async {
    print('    🔧 LocalDatabase.initialize() START');
    
    // Initialize Hive with Flutter (handles path automatically)
    print('    ⏳ Calling Hive.initFlutter()...');
    await Hive.initFlutter();
    print('    ✅ Hive.initFlutter() complete');

    // Register Type Adapters (will be generated by hive_generator)
    // Hive.registerAdapter(UserModelAdapter());
    // Hive.registerAdapter(ChildModelAdapter());
    // Add more adapters as models are created
    print('    ⏳ Registering adapters... (skipped - none yet)');

    // Open boxes
    print('    ⏳ Opening Hive boxes...');
    await _openBoxes();
    print('    ✅ All boxes opened');
    
    print('    ✅ LocalDatabase.initialize() COMPLETE');
  }

  /// Open all Hive boxes
  static Future<void> _openBoxes() async {
    print('      ⏳ Opening box: $_userBoxName');
    await Hive.openBox(_userBoxName);
    
    print('      ⏳ Opening box: $_childBoxName');
    await Hive.openBox(_childBoxName);
    
    print('      ⏳ Opening box: $_pregnancyBoxName');
    await Hive.openBox(_pregnancyBoxName);
    
    print('      ⏳ Opening box: $_visitBoxName');
    await Hive.openBox(_visitBoxName);
    
    print('      ⏳ Opening box: $_immunizationBoxName');
    await Hive.openBox(_immunizationBoxName);
    
    print('      ⏳ Opening box: $_growthBoxName');
    await Hive.openBox(_growthBoxName);
    
    print('      ⏳ Opening box: $_appointmentBoxName');
    await Hive.openBox(_appointmentBoxName);
    
    print('      ⏳ Opening box: $_syncQueueBoxName');
    await Hive.openBox(_syncQueueBoxName);
    
    print('      ⏳ Opening box: $_settingsBoxName');
    await Hive.openBox(_settingsBoxName);
    
    print('      ✅ All 9 boxes opened successfully');
  }

  /// Get box by name
  static Box getBox(String boxName) {
    if (!Hive.isBoxOpen(boxName)) {
      throw Exception('Box $boxName is not open');
    }
    return Hive.box(boxName);
  }

  /// User box
  static Box get userBox => getBox(_userBoxName);

  /// Child box
  static Box get childBox => getBox(_childBoxName);

  /// Pregnancy box
  static Box get pregnancyBox => getBox(_pregnancyBoxName);

  /// Visit box
  static Box get visitBox => getBox(_visitBoxName);

  /// Immunization box
  static Box get immunizationBox => getBox(_immunizationBoxName);

  /// Growth measurement box
  static Box get growthBox => getBox(_growthBoxName);

  /// Appointment box
  static Box get appointmentBox => getBox(_appointmentBoxName);

  /// Sync queue box
  static Box get syncQueueBox => getBox(_syncQueueBoxName);

  /// Settings box
  static Box get settingsBox => getBox(_settingsBoxName);

  /// Clear all data (for logout or testing)
  static Future<void> clearAll() async {
    await userBox.clear();
    await childBox.clear();
    await pregnancyBox.clear();
    await visitBox.clear();
    await immunizationBox.clear();
    await growthBox.clear();
    await appointmentBox.clear();
    await syncQueueBox.clear();
    // Don't clear settings box (keeps language preference, etc.)
  }

  /// Clear only user-specific data (for user switch)
  static Future<void> clearUserData(String userId) async {
    // Remove data for specific user
    await userBox.delete(userId);
    
    // Clear related data (children, pregnancies, etc.)
    final childKeys = childBox.keys.where((key) {
      final child = childBox.get(key);
      return child?.motherId == userId;
    }).toList();
    
    for (final key in childKeys) {
      await childBox.delete(key);
    }
    
    // Similar for other boxes...
  }

  /// Close all boxes
  static Future<void> close() async {
    await Hive.close();
  }
}